BT: Squashed commit of the following data profiles related gerrits
PAN: Fix potential NPE while PAN disconnection.

Use Case:
1. During monkey test.

Failure Logs:
PanService: handlePanDeviceStateChange preState: 0 state: 2
PanService: handlePanDeviceStateChange BT tethering is off/Local role is PANU drop the connection
BluetoothAdapterState: Bluetooth adapter state changed: 15-> 16
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String
 android.bluetooth.BluetoothDevice.getAddress()' on a null object reference
at com.android.bluetooth.pan.PanService.handlePanDeviceStateChange(PanService.java:888)

Root Cause:
In Some conditions, Remote Bluetooth device instance is remains null
because of PAN disconnection.

Fix:
Before fetching remote device address check BT Remote Device
instance Value to avoid NPE.

Change-Id: I01773b657b50392f99004d98dabf21f9704822b5

PAN: Stop inquiry while initiating outgoing connection

If inquiry is going on, then stoping inquiry while initiating
outgoing connection from PANU.

Change-Id: Ic12fcd9e07126f1b7161623cd2ce6566e4260150

OPP: Squashed commit of the following

OPP: Handle Security Exception

Use Case:
1. Pair remote with DUT.
2. Now go to G photos application to share images.
3. Select any image and try share.
4) Cancel operation (Decline Server side)
5) And try share again.

Failure:
"Unfortunately, Bluetooth share has stopped" error comes.

Root Cause:
For security reasons, the permissions are temporary, so once the client
app.s task stack is finished, the file is no longer accessible or some
content providers don't support the read permission.

Fix:
When tap the "try again" button on the send failed dialog, the
method "BluetoothOppSendFileInfo::generateFileInfo()" will be
call, there catching Security Exception and sending empty
BluetoohSendFileInfo.

Change-Id: I4520a91622c0532d7d0f8aeeb7ff76e9a3abe7a1

Opp : Add apk,csv,ogg and ics formats as acceptable inbound types.

Usecase:
Pair with remote and receive apk, csv, ogg and ics files

Failure:
Unable to receive files with above file formats.

Fix:
Adding apk, csv, ogg and ics format as a acceptable inbound types,
to be able to receive these file formats from remote device.

Change-Id: I1d3c3b976822a9147b2b341e19b54bc16c59a94f

Opp : Clean up file when transfer is aborted by remote/local device

Use Case:
1. Send a file from OPP client to OPP Server(DUT).
2. After the incoming file notification comes up.
3. Turn Off Bluetooth and Turn on again or remove battery
   from DUT.

Failure:
- Incoming file notification still present in notification base
- If battery is removed after transfer has started then we see
  incomplete file.

Fix:
Delete File when the transfer is terminated due to
Remotes BT is turned off, remote being taken out of reach or
remote is turned off properly. Also delete the file on the next
reboot while the previous inbound transfer was interrupted by
local device power off, or battery removal.

Change-Id: I61fa66eb96dfc400eda9f8d4d3a8f538c6f05e5f

OPP : Reduce MTU size while simultaneous A2DP and OPP

Use case:
1. Start Low Latency and High Tx Power adv from the DUT
2. From a 2nd DUT scan, connect and pair with the LEP DUT
3. Connect the DUT to a SCO HS
4. Connect the DUT to 2 BR/EDR HID devices
5. Start MO call from the DUT going over SCO
6. Start sending a file from Phone over OPP to the DUT

Result:
After a while the OPP link disconnects
reason: "Connection Timeout"

Fix:
Reduce Obex MTU to 8k if A2DP/SCO are active along
with OPP connection to avoid BT RX fail.

Change-Id: Ib68b1fd1a9c353a79e97699ab12d6253ad89078e

Opp: turn on screen once receiving incoming file
if key guard is set to None, no one will turn on screen when
receiving incoming file. so fix it.

Change-Id: I71bd11923886782949b2296235e5d5876b53ed66

OPP: Broadcast incoming OPP Events to Automation APP.

Usecase:
 1. Run any OPP Server Test case using QSPR
 2. Receive Incoming file request
 3. Current automation based on debug logs are sometimes
    rarely missing the event for incoming files.

Result:
 OPP Server related test cases getting failed.

Root Cause:
 Test app not able to recognize incoming file event

Fix:
 Use Broadcast of intents for test automation purpose instead
 of relying on the logs to capture event.

Change-Id: Icd4a1f6a6e0d64d800e5760c937f0db4ae1c3a51

Opp : Dynamic logging for OPP profile

VERBOSE level logging for OPP profile can be enabled runtime from
adb shell using following command and turn off/on BT:
setprop log.tag.BluetoothOpp VERBOSE -> VERBOSE level Logging

Change-Id: I56d820c89015739321d8b5e121c5fc7f4a2877da

Opp: OBEX service unavailable while doing defensic test.

Usecase:
1. Configure the device with defensics.
2. Run OBEX test suite of Defenices

OBSERVED RESULTS:
OBEX service becomes unavailable after running a particular test case

Fix:
Send MSG_SESSION_ERROR when transfer abort on remote side.

Change-Id: I4d69734ab219df60332604c1677005349c411d42

PBAP: SIM Support, re-factored fixes and 1.2 feature flag.

PBAP: SIM Access support.
This patch adds access to support SIM database while
performing PBAP operations.

Change-Id: Iddace24f43a7618ccbe6a9b49bcab88dbaae0e06

PBAP: Send correct handles of vcard in vcard listing.
    Send correct handles of vcards while responding to pull vcard
    listing request from the server. It was creating the new
    handles of the vcards just before sending the list earlier
    but now it extracts the exact handle from the phonebook append
    that one.

Change-Id: I4b83c5c118a6977e6a14e493d9a23ba439c4a2e2

PBAB: modify method to check whether vcf index is acceptable

Vcf index in phonebook listing is contact id and may exceed the
limitation of size of phonebook so that error occurs while pull
vcard. Check whether vcf index is valid or not by looking
phonebook instead of comparing index value with size of phonebook.

Change-Id: I02f3b6ea9af1322ef066bac9937b50475f9f71df

Disable PBAP 1.2 and PBAP- SIM related features from resource configuration values

following features would be disabled
PBAP-1.2
PBAP-SIM

PBAP-1.2 and PBAP-SIM features is set to false by default. It can be
configured as per need.

Change-Id: I4c5924bd7c94407342c6da83869eaa8da905605d

PBAP: Reduce MTU size while split A2DP, PBAP and AVRCP

Update OBEX MTU equal to RFCOMM frame size so that
OBEX packet can be sent out as single RFCOMM packet and would not
hinder AVRCP packet in queue during concurrent Split A2DP, AVRCP
and PBAP download usecase with specific carkits.

Change-Id: Id7818e6ed68c4105abe6e47e2a628fa2a6e4c5da

PBAP: Fix vCardListing result when searched by number

Usecase:
1) Establish PBAP Session with Carkit.
2) Send GEt vCardListing request with search
   by number.

Issue:
vCardListing fails OBEX_INTERNAL_SERVER_ERROR.

Root Cause:
When contacts are searched by number, phonelookup
doesnt contain account type.

Fix:
When vCardListing is done using search with number,
get account type for given contact from table
(CommonDataKinds.Phone) instead of phonelookup URI.

Change-Id: Iff617dee29bf3869d6d8ec99500ff21d360c1ad2

PBAP: Fix to download local phonebook correctly.

Usecase:
1) Establish PBAP Session with Remote Carkit.
2) Send pull phone request for phone contacts from remote

Issue:
Phonebook download failed.

Root Cause:
Incorrect contact size returned from query for filtering
SIM contact lead to this issue. Change in contactProvider
API for SIM contact aggregation.

Fix:
Fetch all contacts including contacts with account type as
com.android.sim. Then Filter out SIM contacts from PBAP.

Change-Id: Ia10f841243afd823e4ab8eaf4e5e3db408307f9b

MAP: Squashed commit for the following fixes

MAP: [IOT] Fix to remove more than one trailing line feed's in message body.

Usecase:
1) Connect device with carkit.
2) Do Message Listing.
3) Fetch message containing more than 1 trailing Line Feed in the message body end.

Issue:
Message containing more than one trailing line feeds is not displayed on carkit.

Root Cause:
Problem with parsing of remote Carkit for trailing line feeds in message body.

Fix:
Get message body and remove the line feeds present in the end of message.

Change-Id: Ifb8e0de85bc7b373fdadff8f1cf692d6d12fc047

MAP:  Handle following for MAP Server:
-  Remove extra sendshutdownMessage() in onStop() API.
   Regression from N AOSP code.
-  Fix MAP Authorization pop-up dismiss after timeout value.
   Remove setClassName ACCESS_AUTHORITY_CLASS while sendBroadCast
   for BluetoothDevice.ACTION_CONNECTION_ACCESS_CANCEL type intent,
   to avoid explicit intent for
   "com.android.settings.bluetooth.BluetoothPermissionRequest'.
   Implicit intent is required to inform the event to
   "com.android.settings.bluetooth.BluetoothPermissionRequest".
-  Handle MNS OFF for MAS DISC specific to IOT behavior which does not
   send MNS OFF every time before MAS DISC.
-  STOP ObexServersessions (if any)  for ACL_DISCONNECTED event,
   to stop  GET or PUT requests already in process.

Change-Id: Idc9271884259071f195a675bc26caa98887845a0

MAP:  Handle following for MAPS
 - Correct senderName parameter attribute name to "sender_name".
   Add length check to limit the characters  allowed for this
   attribute value to 256, as per the Spec.
- Set default SMS type to SMS_GSM.
- Set default subject, address values to empty for extended
  MNS event report to handle cases for null valued fetched from db.

Change-Id: I3dc787dbf420dbab030713c035a16d935ab64149

MAP: Fix sms move to failed on deliveryFailure.
Avoid movement of sms from  sent folder to  failed
folder on DeliveryFailure Event. Movement of sms
from out box folder to failed folder on SendingFailure
event is only recommended and already handled.

Change-Id: I3f74a0dd5504e13f65f1ab6bafac4115b1698fe3

MAP: Fix parsing special character issue in vcard email.
Replace '<' for '&lt'  and '>' for '&gt' while parsing
email address in vcard pushed from some particular carkits
in MCE role.

Change-Id: Id24d202a6a60b5edb2de11732527135a7542ecd2

MAP:  Handle following for MAPS
- Correct senderName parameter attribute name to "sender_name".
  Add length check to limit the characters  allowed for this
  attribute value to 256, as per the Spec.
- Set default SMS type to SMS_GSM.
- Set default subject, address values to empty for extended
  MNS event report to handle cases for null valued fetched from db.

Change-Id: I3dc787dbf420dbab030713c035a16d935ab64149

MAP: Perform MAS create SDP records from Handler.
Perform MAS Instances create SDP records in Handler
thread instead from main thread to handle possible
ANR while parsing and fetching MAP Email accounts.

Change-Id: I934e90a8e87d1db2cd037d22b0c39e61a8853f62

MAP: MSE MAS Email Instance Support

- Add support MAP Email Instance over L2CAP.

Change-Id: I9c9ded56db491f80a7bc6d7dec68e6f0551612a2

MAP: Limiting supported features to MAP 1.2.

Usecase:
1) Establish Map Session with Remote Carkit.
2) Send MesageListing request from remote with
   MaxListCount as 0 and filtering out MMS and Email.

Issue:
Remote disconnects link with reason "Connection Rejected
due to security reasons".

Root Cause:
Remote carkit supports MAP 1.3 and MAP server(DUT) supports
MAP 1.2. After connection, supported feature mask of MAP
Server is updated to MAP 1.3 feature mask. This leads
sending extra fields in MessageListing Response packet
which may result in remote disconnection.

Fix:
If remote profile supported version is higher than MAP
Server, set profile feature support mask to Server
supported mask.

Change-Id: Ib251e6c225b1ac9b786248e6144939b394b39d3b

MAP: Handle FATAL Exception when two SMS MAS instances are added.

Usecase:
Turn Bluetooth ON-OFF for multiple times(at least 100)

Issue:
FATAL Exception because of ArrayIndexOutOfBound when two SMS
MAS instances are added.

Root Cause:
createMasInstances() was getting called twice and in race condition
when Handler thread and main thread adds SMS MAS instance in
Sparse Array, two MAS instances were added for SMS.

Fix:
Remove duplicate call to createMasInstances(). createMasinstance()
will only be called from Handler Thread.

Change-Id: Id00d37e74f6d79f2b471714a0a1f9a0acd6f623b

MAP: Add write SMS protection

This change prevents local application to delete stored SMS messages
which does not use or request the WRITE_SMS permission.

Change-Id: I1ef6afa00f67bb685a0380d9bc3568a4be761910

Bluetooth: Support for fixed RFCOMM channel and L2CAP PSM.

This change contains support for fixed RFCOMM channel and
L2CAP PSM for all obex based profiles and SAP.

Usecase:
1) Connect with specific Carkit.
2) Sync contacts from carkit

Issue:
Carkit can not get contacts via PBAP as DUT
rejects OBEX connect request for PBAP.

Root cause:
Carkit issues OBEX connect request for PBAP on
channel that is used by some other profile due to
dynamic channel allocation after BT reset.

Fix :
Use fixed channel number for RFCOMM and Fixed PSM for L2CAP
for all OBEX based profiles as well as SAP.

Change-Id: I9f57337ef8bed132655d8d3875040dfcc12f81fc

AVRCP 1.6: Add support for coverart

Add support for cover art feature in AVRCP.
Change-Id: Ic3f03a99de6c7c0e4999e287a0efb0fe76819033

CRs-Fixed: 2196545
Change-Id: Ia66a3d6dfcc2ac4c2f919b3c09a622dac5cff1bf